### PR TITLE
Fix to Bug removing shards from forged items #146

### PR DESCRIPTION
**Pull request by NeiaC**

### CODE REVIEW

**Comment by merung** [comment]
I do not like the idea of displaying skill levels. I would prefer this to be just a fix for the bug.

**Comment by NeiaC** [comment]
Reverted. The clarification of skill level requirements weren't meant to be in the bugfix pull request.

**Comment by merung** [comment]
I think it can be merged

**Comment by estralis** [comment]
Merged. Thank you very much for the contribution!

**Pull request merged**
