### PR TITLE
Feature/simplified housing

### PR DESCRIPTION
**Pull request by Brightrim**
An overview for anyone wanting to test, as suggested by Vilarion:
Local server link: 
https://github.com/Illarion-eV/Illarion-Dev

Scripts branch: 
https://github.com/Brightrim/Illarion-Content/tree/feature/simplified_housing

Maps branch: 
https://github.com/Brightrim/Illarion-Map/tree/feature/simplified_housing

Database changes:
```sql
UPDATE items SET itm_script = 'item.notice' WHERE itm_id IN (3772, 3773);
UPDATE items SET itm_script = 'item.builderstool' WHERE itm_id = 2697;
INSERT INTO scheduledscripts VALUES ('scheduled.rent', 600, 600, 'rent');
```
What to test:
1. Property deeds and their functionalities. Admin characters and player leaders have full access, regular characters have limited access. The deeds can be found at any rentable property, including free-build estates outside of town (EG: One is at each harbour).
2. Property functionalities on the ceiling trowel GM tool, for ease of management and for managing properties that do not have property deeds (namely outlaw ones, of which there is currently only one made.)
3. The building tool (Do !create 2697 to get one) and its functionalities. Limited for town properties. Free-build for estate properties outside of town.
4. Key retrieval. Any keys you are not meant to have should be removed from your inventory or depot upon logging in.(admins are allowed to have all keys, player leaders those of their town, regular characters only those of the property they rent or are guests of).
5. Any misc. events that can be thought of. EG: What happens to properties and keys if you change citizenship?(Already accounted for, just an example)

--------
Planned changes:
- Better names for craftable doors/gates/walls to include the direction they face, since neither the graphic or database names reflect this making it difficult to know before you craft them.
- Potentially go back to making tiles persistent upon changes being made rather than on reload
- Potentially changing the item used as a building tool
- Include a way to obtain a building tool
--------
Original comment:
- Adds property deeds to every rentable property (see map changes)
- Regular players may check these for information on the property
- Administrators and town leaders may change the rent, renter, rent duration, guests and required rank shown
- Keys will be "confiscated by guards" if you are not allowed to have them
Requires map changes in order to add the property deeds for each item.
Requires database changes:
Items 3772 and 3773 must have the notice script added to them
The scheduled rent script must be added to scheduled scripts, something like 600-600 for time will do

### CODE REVIEW

**Comment by Brightrim** [comment]
Note: I also have scripts that will allow for _full_ automation where the renter can rent, set guests, pay rent, extend rent, etc on their own while the town leaders can collect the rent via the town management tool, if it should be desired.

**Comment by Brightrim** [comment]
Update:
Added sandboxing along with 10 new properties outside of town for free-building. Tenants of properties inside town will now have limited building functions to use that allows them to change furniture, but not to change the properties structure itself. 
Tenants of the new properties will have free reign within the property limits, including a basement, floor 0, 1 and 2. 
Currently three such properties exist per town. 
Outlaws will also be able to free build on a property if a GM permits it. Functionality for this has been added to the GM tool, and additional functionality exists for outlaws on the builder's tool in order to replace the property deed, due to the nature of outlaws. 
Currently one outlaw property exists. 
Additonal properties can easily be added with some script changed in the list of properties in the notice.lua file and propertyList.lua file, though one should remember to document what key is assigned to the property in the keys documentation. 

Additional Map Changes Required: 
Basement maps must be uploaded, see related map content pull request. If they are not uploaded before launching the server with the scripts, they will spawn without tiles because of persistent tiles saving them as tile-less. 

Additional Database Changes Required: 
item 2697 must have script item.builderstool applied 

Known issues: 
German translation is missing or lacking in several areas. Since the scripts still need to be reviewed, bug tested and changes may very well be requested to it, I see no need to finalize translations for English text that may very well be different in the end result, before reviewing is done. 

Often times you have to navigate the dialog menu twice in order to open a crafting menu. Presumably due to an inherent flaw in selectiondialogs interacting with a craftingdialog? 

All the persistent files makes server start-up take around a minute longer. Insignificant issue. 

Upon server startup there have been rare occasions where only persistent files load and not map files. A map reload resolves this, but player are able to log in before a map reload and will log in to an empty map if not on a persistent tile. 

Had to separate crafting dialogs into several smaller ones, or else they refused to load properly due to the significantly large amount of items. 

While levels and ingredient requirements have been assigned to every single buildable item, it is not necessarily balanced and will require a thorough review if we want to allow learning in the related skills when crafting for houses. However currently a string of code has been put in place to prevent learning if you are crafting for a house, and you can't sell the product (other than to the player that potentially hires you as a builder, agreeing on a builders fee) so I do not think balance is necessarily an issue.

**Comment by estralis** [comment]
Hey, my review will take some time as I'm working 100 % on the tutorial. One thing that caught my attention, you want to use the rasp (2697) as a building tool. Did you check it is not in use as e.g. NPC trader stock, monster drop, treasure chest content,...?

We can probably think about adding a completely new item or use merge both trowel GM items into one and use the "free" trowel.

**Comment by Brightrim** [comment]
> Hey, my review will take some time as I'm working 100 % on the tutorial. One thing that caught my attention, you want to use the rasp (2697) as a building tool. Did you check it is not in use as e.g. NPC trader stock, monster drop, treasure chest content,...?
> 
> We can probably think about adding a completely new item or use merge both trowel GM items into one and use the "free" trowel.

I only used the rasp as it was the only tool I could think of that has no current uses. I neither checked whether it can be found in trader stock, monster drops or treasure chest content nor did I implement a way to actually obtain it for building purposes. This because I expected it may very well be changed into using another tool, however if it is desired to keep the rasp as the tool and not just temporarily for testing then I can go about doing that.

Though whether it is that, merging the GM trowels and using one of them or adding a new item, just let me know what's desired. Changing it from the rasp to something else isn't much work as I anticipated it might happen.

**Comment by estralis** [comment]
Thank you very much! We'll see what the best solution is. Swapping an ID is easily done. For testing and further steps, it is absolutely OK to use the rasp as it indeed has not other use today.

**Comment by vilarion** [comment]
Up-front loading times for persistent tiles are a concern, not so much for production, but for developers, constantly restarting their server. I will look into making this more efficient. Otherwise we might need to setting persistence on demand instead of up front.

Some map items with stack size 0 are creating problems, because the db expects stack size >= 1. I will look into why this happens.

**Pull request closed without merging**
